### ISSUE TITLE
Requiring a global export module twice fails

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-amd-loader#48] opened 2016-01-29 13:10 UTC
Currently, trying to require a global module with an export variable will fail

```javascript
Loader.addModule({
    dependencies: [],
    exports: '_',
    name: 'underscore',
    path: '/modules2/underscore.js'
});

Loader.require(['underscore'], success, failure);
Loader.require(['underscore'], success, failure);
```

The problem is that the second require will get to the [`_createModulePromise`](https://github.com/liferay/liferay-amd-loader/blob/master/src/js/script-loader.js#L245) function since the module was already requested, but this will happen before the [`pendingScripts`](https://github.com/liferay/liferay-amd-loader/blob/master/src/js/script-loader.js#L465) promises are resolved. Because of this, it will try to find the exported value even before the script has finished loading.

I think we should try to wrap the exports check in a listener as well, and somehow emit it upon script loading so the behaviour matches that of the other modules.

@ipeychev, what do you think?

**Comment by jbalsas** [comment] 2016-01-29 13:34
Hey Iliyan, I was trying this:

https://github.com/jbalsas/liferay-amd-loader/commit/3b357704e5556c20b7cfd5ef7d8ff33a84510933

It fixes the case when two requires are done consecutively but not if only one is executed. What do you think? Is this the right approach?

**Comment by ipeychev** [comment] 2016-01-29 14:50
Hey Chema,

Interesting, I just added a [test](https://github.com/liferay/liferay-amd-loader/commit/ae60d5fc8cc5eeb6c43b4010556db501bfe17465?diff=unified#diff-f54552afe6d8702b421fa36d2648000bR578) which covers that on the existing code and it passes?

**Comment by ipeychev** [comment] 2016-01-29 14:56
In addition to the comment above, maybe more debugging is needed here, because the situation with requesting same module twice was considered - the second `require` won't add a new promise, but just wait for the first one to fulfill. If already fulfilled, the `success` will be invoked directly (I simplified it, but in general this is the picture). That's how it is designed to be and from architectural point of view I don't see any issue with this?

**Comment by jbalsas** [comment] 2016-01-29 14:57
Hey Iliyan, that's because the tests are not cleaning after them properly,
so you're grabbing the already loaded underscore from before.

Try running just one and the error should pop up ;)

**Comment by ipeychev** [comment] 2016-01-29 15:22
Wow, since this is a global variable, it really does not clean it :(
And yes, I was able to reproduce it when cleaning after the tests which expose global variables, thanks for the heads up.

**Comment by ipeychev** [comment] 2016-01-30 05:48
Hey Chema,

I extended your commit so things now work and committed it to master with your name as author to not steal from your glory :)
The tests pass now, so could you please check if it works for you too? If so, we will release a new version.

The downside here is that we are introducing a new event. With "real" modules, we don't have a choice, except listening to an event, since they may `define` a module not necessarily immediately after the script is being loaded, but a few seconds later. However, with these global modules, which don't call `define`, we could look for the exported properties immediately after script loading (after script promises resolving). Thinking about such an implementation, I'm not sure if it will be simpler than an event. What do you think?

Thanks,

@jbalsas

**Comment by jbalsas** [comment] 2016-01-31 15:47
Hey Iliyan, thanks a lot for working on this and sharing the glory! You know I'm not so concerned about it, but's good to be sharing it with you :wink: 

There's a small issue, so I've reopened this and sent a followup https://github.com/liferay/liferay-amd-loader/pull/50

We need to check that the script loaded is the one supposedly exporting the variable, otherwise, we might try to do that for other scripts when more modules are being loaded.

I'm still not that fluent with the architecture of the loader, so I think this is at least good enough for now.

**Closed** 2016-01-31 22:15 UTC
Labels: bug
