### ISSUE TITLE
Import problem with amCharts

### ISSUE THREAD

**Issue by caneta** [liferay/liferay-amd-loader#130] opened 2017-05-03 14:13 UTC
I have an import problem with a plugin named [amCharts](https://www.amcharts.com/).
I get it work, but the code is pretty ugly:
```

Loader.addModule({
  name        : 'amcharts',
  anonymous   : true,
  dependencies: [],
  exports     : 'AmCharts',
  path        : 'my-plugins/amcharts/dist/amcharts/amcharts',
});

Loader.addModule({
  name        : 'pie',
  anonymous   : true,
  dependencies: ['amcharts'],
  exports     : 'AmCharts.AmPieChart',
  path        : 'my-plugins/amcharts/dist/amcharts/pie'
});

Loader.require(['amcharts'],
  function (amcharts) {
    Loader.require(['pie'],
      function (pie) {
        console.log(AmCharts);
        console.log(AmCharts.AmPieChart);
      },
      function (error) {
        console.error(error);
    }); // require()
  },
  function (error) {
    console.error(error);
}); // require()
```
The problem is that **pie** should be loaded only after **amcharts** is already in place and the _window.AmCharts_ object is available.

How to deal with dependency or META (with a trigger test maybe?) in order to be sure to load one after the other?

Thank you

**Comment by izaera** [comment] 2017-05-04 12:54
Hi @caneta:

I'm not 100% sure of what you are trying to achieve.

You mean that nesting the `require('amcharts')` and `require('pie')` is ugly?

In that case, isn't `require('pie')` alone working to load both modules? It should, as `pie` depends on `amcharts`...

**Comment by caneta** [comment] 2017-05-04 13:01
Hi @izaera 
> isn't require('pie') alone working to load both modules?

This would exactly be my goal, but I don't know how to achieve it.

I've tryied several ways but I cannot make it work: the dependency set in Loader.addModule is not enough.

If I try to require pie module only, amcharts is not loaded before it, and I got an error because the AmCharts object is not available yet...

**Comment by ipeychev** [comment] 2017-05-04 13:43
That is odd, `require('pie')` should be enough. I would guess that these exports and not the correct ones, but if it works when you load them one by one, then it should be something else.
Would it be possible for you to prepare a zip file with these plugins and a simple HTML page, which loads these plugins using `require('pie')` only? Then we will debug and check.

Thanks,

**Comment by caneta** [comment] 2017-05-05 15:24
Hey, @ipeychev here you are [an example](https://github.com/caneta/liferay-experiments/tree/master/loadcharts).

I'm using Liferay CE GA3 patched with the [LPKG override method](https://github.com/liferay/liferay-portal/blob/master/tools/osgi-marketplace-override-README.markdown) in order to have a more recent version of the loader.

On the original GA3 there is the AMD Loader 1.5.2, and with my patch I've upgraded it to the 1.5.5. It is not the latest one because I'm working on this project since a while...

But...my example seems working outside the Liferay environment! Even with the 1.5.5 version...try it yourself with my example.

So I'm guessing if this could be a problem of my patch: I've updated inside `bundles/osgi/marketplace/Liferay CE Foundation.lpkg/com.liferay.frontend.js.web.jar/......` only the _loader.js_ file.

Am I missing something, maybe?

Thank you.

**Comment by izaera** [comment] 2017-05-08 08:22
Hi @caneta:

I have run your example and I can confirm that it is a loader issue. The problem only arises when using modules with `exports` which are not defined using AMD's `define` function.

As you said, doing a require with `amcharts`, followed by a require of `pie` in the callback works because the scripts are loaded and executed in the proper order. That way, `pie` module finds `window.AmCharts` correctly populated.

But, when you request `pie` directly, the loader traverses the dependencies of `pie` and inserts two DOM SCRIPT nodes (one for `amcharts`, and another one for `pie`) so that the browser loads them. Then it waits for the sripts to load and stores their implementations (`window.AmCharts` and `window...Pie`) in its module registry.

The problem is that because these modules are not AMD modules, but direct Javascript code putting things inside `window`, sometimes the `pie.js` file is loaded before `amcharts.js` because the browser decides to load them in that order. And when that happens there's no way for the loader to control the execution of the code inside `pie.js` and `amcharts.js` so it runs in the incorrect order (`pie` before `amcharts`).

It can be fixed by inserting the DOM nodes in the correct order, and wait for the `amcharts.js` one to be loaded and executed before the `pie.js` is even inserted in the DOM. 

Sadly, this is not so straightforward to implement because it would hurt performance, so we must give it a thought to, perhaps, do it only when modules with `exports` are used or some kind of heuristic like that...

For now, I would advice to use the double require as a workaround until we fix this.

/CC @ipeychev

**Comment by caneta** [comment] 2017-05-08 09:52
I like the implementations only for the `exports` case, it seems realistic to me: plugins conceived from the beginning with an AMD architecture probably do not need this...

**Comment by ipeychev** [comment] 2017-05-08 19:54
Hey @caneta,

Could you please change the version of loader in your example to this:
```
"liferay-amd-loader": "git+https://git@github.com/liferay/liferay-amd-loader.git#fix-130",
```

and try this [fix](https://github.com/liferay/liferay-amd-loader/commit/92bc988594181741509449990b51bd707bec1538)?

Thanks,

**Comment by caneta** [comment] 2017-05-09 08:27
I've tryied to use the version you suggested in my example and it worked, but it worked with version 1.5.5 too.

But the important thing is that now works in the Liferay environment too!
I've overriden the loader with the fixed version inside the Liferay Portal, and now requiring **pie** only, it loads **amcharts** before!

**Comment by ipeychev** [comment] 2017-05-09 08:51
It worked with version 1.5.5 too? What do you mean? In your [example](https://github.com/caneta/liferay-experiments/blob/a4692a6fa3ea5962dad2b3658dee6efbbc3197e4/loadcharts/package.json#L13) the version of loader was 1.5.5 and it didn't work?

**Comment by caneta** [comment] 2017-05-09 08:58
As I wrote above:
> I'm using Liferay CE GA3 patched with the LPKG override method in order to have a more recent version of the loader.
On the original GA3 there is the AMD Loader 1.5.2, and with my patch I've upgraded it to the 1.5.5. It is not the latest one because I'm working on this project since a while...
But...my example seems working outside the Liferay environment! Even with the 1.5.5 version...try it yourself with my example.

I don't know why outside Liferay it works even with an old version of the loader, and inside Liferay it doesn't work.

Now with your fix the single **pie** require works inside Liferay too: that didn't happen before.

**Comment by ipeychev** [comment] 2017-05-09 09:06
Umm, yesterday I downloaded your example, where the version is 1.5.5 and it didn't work, that's why I went to fix it. 1.5.5 didn't work for @izaera neither, as he wrote [here](https://github.com/liferay/liferay-amd-loader/issues/130#issuecomment-299803803).

Anyway, glad that it works now, so @jbalsas and @izaera, could you do a test of that fix and merge it?

Thanks,

**Comment by caneta** [comment] 2017-05-09 09:24
I've retried right now with the original code of my example (loader-1.5.5) and it does not work indeed: maybe I made some mess testing it the first time.

I've [updated my example](https://github.com/caneta/liferay-experiments/commit/5c97b1e8c34459e4f64f9e785ae84fb915975b49) with the fixed loader.

Thank you @ipeychev

**Comment by izaera** [comment] 2017-05-09 14:29
Just a quick note to say that the bug (with the old loader, without the fix) was not always reproducible, because it depended on the order the browser loaded the two scripts (pie and amcharts). 

So, without the fix, it may sometimes fail and sometimes work (without changing the application code).

**Comment by izaera** [comment] 2017-05-10 07:04
@ipeychev I have tried to reproduce the bug again after updating my Chrome browser and it does not happen any more so I can't verify your fix :-( . Nevertheless it looks like placing `async=false` would make it more robust and fix the issue, so I would merge it.

I attach a link with more info about how the `script` tags behave in different browsers in case it is needed for future reference -> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Browser_compatibility

**Comment by jbalsas** [comment] 2017-05-10 07:18
Sounds good to me too 👍

**Comment by izaera** [comment] 2017-05-10 07:58
As agreed with @jbalsas, I will send a PR with @ipeychev's fix and will try to add a test for the fix.

**Closed** 2017-05-11 09:22 UTC
Labels: bug
