### ISSUE TITLE
Load a jQuery plugin fullCalendar

### ISSUE THREAD

**Issue by luisbritosilva** [liferay/liferay-amd-loader#139] opened 2017-05-18 12:47 UTC
Hi guys,

Following the steps described by @caneta, @yuchi, @ipeychev in the previous issues #80 and #82, I am trying to get working this jQuery calendar plugin: [fullCalendar](https://github.com/fullcalendar/fullcalendar)

I am running Liferay 7 EE with installed patch de-13-7010.

I followed @yuchi suggestion and have jquery AMDify, and followed @caneta steps to configure the Loader to handle the JS as plugin through the exports property.

You can find the example [here](https://github.com/luisbritosilva/liferay-amd-loader-examples)

If you check the browser console one can see that the loader initializes well the jquery and moment (both dependencies needed by fullCalendar) but when running the require for fullCalendar it fails with the console error message "The resource from “http://localhost:8080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7010&t=1495104770270&moment.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)"

Any ideas what I am doing wrong?

**Comment by ipeychev** [comment] 2017-05-18 13:43
I'm not sure this is your fault or Loader's one. `X-Content-Type-Options: nosniff` will block a request in a script if MIME type is not a JavaScript MIME type. Here is what is considered as [JavaScript MIME type](https://html.spec.whatwg.org/multipage/scripting.html#javascript-mime-type).

What are the headers of this request? You may post them here, or save the request as HAR and attach it here.

**Comment by luisbritosilva** [comment] 2017-05-18 14:20
Follows the HAR with all requests made. The one that is generating the MIME type mismatch has error code 500
[github - #139 - Archive 17-05-18 15-14-12.zip](https://github.com/liferay/liferay-amd-loader/files/1011175/github.-.139.-.Archive.17-05-18.15-14-12.zip)

**Comment by caneta** [comment] 2017-05-18 14:22
@ipeychev, I think this is not a Loader issue too.
@luisbritosilva check [my pull request,](https://github.com/luisbritosilva/liferay-amd-loader-examples/pull/1) this works for me!

**Comment by ipeychev** [comment] 2017-05-18 14:41
Well, we know now: a resource is requested via script, the server returns 500 instead JS code, `Content-Type` is text/html, there is `X-Content-Type-Options nosniff`, hence the browser discards this script.

Thanks, @caneta for taking care about that too!

**Comment by luisbritosilva** [comment] 2017-05-18 17:52
Thanks @caneta your pull solved the call to the fullCalendar, which is now working, but ;)
 My goal is to have [Scheduler ](https://github.com/fullcalendar/fullcalendar-scheduler) which is an add-on of fullCalendar working and so having the first snag being solved I added the scheduler.js and now I am having the same problem but latter when the require calls scheduler.js....

Any ideas what I am doing wrong?

**Comment by luisbritosilva** [comment] 2017-05-28 17:05
Hi  @caneta, @yuchi, @ipeychev 
Any ideias how should I define at Liferay Loader the scheduler.js so that is successfully loaded by the portal?
Thanks for your help ;)

**Comment by izaera** [comment] 2017-05-30 13:06
@luisbritosilva I have tried your example in the latest development version of Liferay Portal (master branch) and it works. 

I'm now trying with version 7.0.0 to determine if it has been fixed by any of the latest features we have added or it is just that I cannot reproduce it for some reason...

**Comment by izaera** [comment] 2017-05-30 15:04
I can confirm that it looks like working for me (using 7.00 de-13-7010). 

Can you provide more feedback about what is failing? I'm getting this after deploying your example:

![image](https://cloud.githubusercontent.com/assets/3273630/26590062/f28803ea-4559-11e7-9ae8-b94b71f7b327.png)

**Comment by luisbritosilva** [comment] 2017-06-02 15:05
Thanks @izaera it is working :)
I refreshed the portal environment and now everything is running ;)

**Comment by jbalsas** [comment] 2017-06-02 15:17
Thanks @izaera, and @luisbritosilva for double-checking and letting us know! :)

**Closed by jbalsas** 2017-06-02 15:17 UTC
Labels: help wanted, question
